### ISSUE TITLE
Add documentation on internals

### ISSUE THREAD

**Issue by javierhonduco** [facebookexperimental/rbperf#10]
We don't have much documentation on how rbperf works from a high level perspective

**Comment by sumerc** [comment]
Hi. 

Is there any progress on this or will there be :)? Even a simple document outlining how threads are retrieved/callstacks are read etc might be very helpful. If there is something that I can help with, I would be willing to help.

**Comment by javierhonduco** [comment]
Hey @sumerc! Yes, haven't forgotten about this! 

Sorry for the delay, I'm a bit busy at the moment, but can try outline the high-level internals here if this could be helpful
