### ISSUE TITLE
Use standard shared-based Ruby builds with asdf in tests?

### ISSUE THREAD

**Issue by sitano** [facebookexperimental/rbperf#25]
What do you think of moving to the use of `asdf` (https://asdf-vm.com/) for `tests/rubies` instead of using `git lfs` and custom static binaries builds?

I am going to add Ruby 2.4.10, and thought that the current approach is a bit cumbersome. Test framework could use just `$(asdf where ruby 2.5.0)/bin/ruby` instead.

Also, probably ruby binary for version 2.5.0 is invalid. It checksum matches 2.4.4 version.

It's just a question. What do you think?

Feel free to close it.

**Comment by javierhonduco** [comment]
Hi!

I agree that the current approach is quite cumbersome 😞 . It's something I've been wanting to change but didn't have the time yet. Hope to revamp it before end of year. Was thinking on running (Docker ?) containers instead, as they already have pre-built Rubies for pretty much every version. This would also be better for development as I run rbperf in a VM that doesn't support nested virtualisation unfortunately.

Either way, I would definitely accept a PR that adds 2.4.10! And thanks for the heads up on 2.5.0, will take a look at that!

**Comment by sitano** [comment]
Great!

@javierhonduco if you are willing to accept a PR that will replace the `tests/rubies` with the use of `asdf` I think I can also make one. Just let me know. Until then, I will build a static one.

In `asdf` scenario the requirement for running tests will be:

- having `asdf` in $PATH
- bin/test will check all needed versions are present by making something like asdf install ruby X.X.X
- test/* will do the rest

**Comment by sitano** [comment]
btw, thank you for this profiler! I think it's a great idea.
