### ISSUE TITLE
Could not install protobuf when run sudo python3 setup.py

### ISSUE THREAD

**Issue by jes2ica** [facebookexperimental/rbperf#6]
Hi!

I was trying to install rbperf on my linux machine, but got the following error when installing protobuf:

```
Processing dependencies for rbperf==0.1.0
Searching for protobuf
Reading https://pypi.org/simple/protobuf/
Download error on https://pypi.org/simple/protobuf/: [Errno 99] Cannot assign requested address -- Some packages may not be found!
Couldn't find index page for 'protobuf' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno 99] Cannot assign requested address -- Some packages may not be found!
No local packages or working download links found for protobuf
error: Could not find suitable distribution for Requirement.parse('protobuf')
```

**Comment by javierhonduco** [comment]
Is it possible that you might have `pypi.org` blocklisted or the network disabled or firewalled?  Could you try `curl https://pypi.org/` and running pip with `--verbose`?

Thanks!

**Comment by jes2ica** [comment]
Yes I think you are right! Is there a way to get around this?

**Comment by javierhonduco** [comment]
I am afraid you will need an internet connection to download the dependencies from pypi. I think the easiest thing to do would be to allow pypi connections / enable networking. Alternatively, if you maintain your own python package index, you can try [to point to it](https://stackoverflow.com/questions/24443583/using-an-extra-python-package-index-url-with-setup-py)
